# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from audioserve.proto import audioserve_pb2 as audioserve__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in audioserve_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioServeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.unary_unary(
                '/audioserve.v1.AudioServe/Transcribe',
                request_serializer=audioserve__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=audioserve__pb2.TranscribeResponse.FromString,
                _registered_method=True)
        self.TranscribeWithDiarization = channel.unary_unary(
                '/audioserve.v1.AudioServe/TranscribeWithDiarization',
                request_serializer=audioserve__pb2.DiarizeRequest.SerializeToString,
                response_deserializer=audioserve__pb2.DiarizedTranscribeResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/audioserve.v1.AudioServe/ListModels',
                request_serializer=audioserve__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=audioserve__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/audioserve.v1.AudioServe/HealthCheck',
                request_serializer=audioserve__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=audioserve__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class AudioServeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Transcribe(self, request, context):
        """Transcribe audio (ASR only)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TranscribeWithDiarization(self, request, context):
        """Transcribe audio with speaker diarization
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """List loaded models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioServeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=audioserve__pb2.TranscribeRequest.FromString,
                    response_serializer=audioserve__pb2.TranscribeResponse.SerializeToString,
            ),
            'TranscribeWithDiarization': grpc.unary_unary_rpc_method_handler(
                    servicer.TranscribeWithDiarization,
                    request_deserializer=audioserve__pb2.DiarizeRequest.FromString,
                    response_serializer=audioserve__pb2.DiarizedTranscribeResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=audioserve__pb2.ListModelsRequest.FromString,
                    response_serializer=audioserve__pb2.ListModelsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=audioserve__pb2.HealthCheckRequest.FromString,
                    response_serializer=audioserve__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'audioserve.v1.AudioServe', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('audioserve.v1.AudioServe', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioServe(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audioserve.v1.AudioServe/Transcribe',
            audioserve__pb2.TranscribeRequest.SerializeToString,
            audioserve__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TranscribeWithDiarization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audioserve.v1.AudioServe/TranscribeWithDiarization',
            audioserve__pb2.DiarizeRequest.SerializeToString,
            audioserve__pb2.DiarizedTranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audioserve.v1.AudioServe/ListModels',
            audioserve__pb2.ListModelsRequest.SerializeToString,
            audioserve__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audioserve.v1.AudioServe/HealthCheck',
            audioserve__pb2.HealthCheckRequest.SerializeToString,
            audioserve__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
